version: "3"
services:
  alpine:
    build:
      context: .
    # Nginx will probably have to access servers on the host so isolating it is pointless
    network_mode: host
    restart: always
    volumes:
      # The certificates will be stored here
      - ./letsencrypt:/etc/letsencrypt
      # The configuration file
      - ./config.yml:/mount/config.yml
