version: '3'
services:
  https-proxy:
    build:
      context: .
    ports:
      - 80:80
      - 443:443
    environment:
      URL: http://host.docker.internal:8080/
      HTTP_PORT: 80
      HTTPS_PORT: 443
      KEY_PATH: /mount/letsencrypt/live/example.com/privkey.pem
      CERT_PATH: /mount/letsencrypt/live/example.com/fullchain.pem
      STATIC_PATH: /mount/certbot-static/
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /etc/letsencrypt/:/mount/letsencrypt/
      - /tmp/certbot-static/:/mount/certbot-static/
    restart: always
