version: '3'
services:
  # Alpine based Nginx + Certbot + Cron combo:
  alpine:
    build:
     context: .
    # Nginx will probably have to access servers on the host so isolating it is pointless
    network_mode: host
    volumes:
      - ./letsencrypt:/etc/letsencrypt # The certificates will be stored here
      - ./config.yml:/mount/config.yml # The configuration file
