version: "3"
services:
  alpine:
    build:
      context: .
    # Nginx will probably have to access servers on the host so isolating it is pointless
    network_mode: host
    restart: always
    volumes:
      # The certificates will be stored here
      - ./letsencrypt:/etc/letsencrypt
      # The configuration file cannot be mounted directly because recreating it
      # would render the container stuck with the old configuration until a restart
      # Thus we mount the whole parent directory instead
      - .:/mount
